config/routes.rb
Rails.application.routes.draw do
  resources :movies
  devise_for :users

  get '/' => 'movies#index'
  get '/buy/:id' => 'orders#buy', as: :buy
  post '/order/:id' => 'orders#create'

  get '/admin' => 'admins#index'
  get '/auditorium/new' => 'admins#new_auditorium'
  post '/auditorium/create' => 'admins#create_auditorium'
  get '/sales' => 'admins#sales'
  get '/showing/new' => 'admins#new_showing'
  post '/showing/create' => 'admins#create_showing'
end

app/models/auditorium.rb
class Auditorium < ActiveRecord::Base
  has_many :showings

  validates :seating_capacity, numericality: { only_integer: true }
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  has_many :showings
end

app/models/order.rb
class Order < ActiveRecord::Base
end

app/models/role.rb
class Role < ActiveRecord::Base
end

app/models/showing.rb
class Showing < ActiveRecord::Base
  belongs_to :movie
  belongs_to :auditorium

  has_many :users, through: :tickets
  has_many :tickets

  # validates :start_time :if => :other_movie_overlap?

  def remaining_seats
    auditorium.seating_capacity - tickets.count
  end
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :user
  belongs_to :showing

  validates :name, :email, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role

  has_many :tickets
  has_many :showings, through: :tickets
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController

  before_action :authenticate_admin!
  
  def index
  end

  def new_auditorium
  end

  def create_auditorium
    auditorium = Auditorium.new(
      seating_capacity: params[:seating_capacity]
      )

    if auditorium.save
      flash[:success] = "You created auditorium number #{auditorium.id}, with a seating capacity of #{auditorium.seating_capacity}"
    else
    end
    redirect_to '/admin'
  end

  def sales
    @movies = Movie.all

    if params[:movie_id] && params[:movie_id] != 'all'
      movie = Movie.find(params[:movie_id])
      @tickets = Ticket.joins(:showing).where("showings.movie_id = #{params[:movie_id]}")
    else params[:movie_id] == 'all'
      @tickets = Ticket.all
    end

  end

  def new_showing
    @movies = Movie.all
  end

  def create_showing
    start_time = "#{params[:start_time]["(1i)"]}-#{params[:start_time]["(2i)"]}-#{params[:start_time]["(3i)"]} [#{params[:start_time]["(4i)"]}:#{params[:start_time]["(5i)"]}:00]"

    # YYYY-MM-DD [HH:MM:SS]

    p start_time
    puts params[:start_time]
    showing = Showing.new(
      auditorium_id: params[:auditorium_id],
      movie_id: params[:movie_id],
      start_time: start_time
      )

    if showing.save
      flash[:success] = "You created a new showing of #{Movie.find(params[:movie_id])}"
    end
    redirect_to '/admin'
  end

  private

  def authenticate_admin!
    unless current_user
      redirect_to '/movies'
    end
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  
  def configure_devise_params
    devise_parameter_sanitizer.for(:sign_up) do |u|
      u.permit(:role_id, :email, :password, :password_confirmation)
    end
  end

  def after_sign_out_path_for(resource_or_scope)
    "/"
  end

  def after_sign_in_path_for(resource)
    '/'
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  before_action :authenticate_admin!, :except => [:index, :show]

  def index
    @movies = Movie.all
  end

  def show
    @movies = Movie.all
    @movie = Movie.find(params[:id])
    @showings = @movie.showings.order(:start_time)
  end
  def new
    @movie = Movie.new
  end

  def create
    @movie = Movie.create(
      title: params[:title],
      description: params[:description],
      duration: params[:duration],
      image_url: params[:image]
    )    
    redirect_to '/movies'
  end

  def edit
    @movie = Movie.find(params[:id])
  end

  def update
    @movie = Movie.find(params[:id])
    @movie.update(
      title: params[:title],
      description: params[:description],
      duration: params[:duration], 
      image_url: params[:image]
      )
  end

  def destroy
    movie = Movie.find(params[:id])
    movie.delete
    flash[:danger] = "You deleted #{movie.title}"
    redirect_to '/'
  end

  private

  def authenticate_admin!
    unless current_user
      redirect_to '/movies'
    end
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def buy
    @showing = Showing.find(params[:id])
  end

  def create
    showing = Showing.find(params[:id])
    if showing.remaining_seats < 1 
      flash[:warning] = "Sorry, this show has sold out"
    end

    if params[:credit_card_number].length == 10 && params[:expiration_date]
      order = Ticket.new(
        name: params[:name],
        email: params[:email],
        showing_id: params[:id]
        )
      if order.save
        flash[:success] = "Ticket purchased. Receipt sent to #{params[:email]}"
      else
        flash[:danger] = "Ticket purchase failed. Make sure you entered your name and email (or you should have hired a developer with more experience!)"
      end
    else
      flash[:warning] = "Either your credit card is invalid, or you forgot the expiration date. Or you're broke."
    end
    redirect_to '/'
  end

end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/admins/index.html.erb
<div class="container">
  <a href="/auditorium/new">Create new Auditorium</a><br />
  <a href="/showing/new">Create new showing</a><br />
  <a href="/sales">View sales</a><br />
  <a href="/movies/new">create new movie</a>

</div>

app/views/admins/new_auditorium.html.erb
<h1>New Auditorium</h1>

  <%= form_tag '/auditorium/create', method: :post do %>
    <div class="form-group">
      <%= label_tag :seating_capacity %>
      <%= text_field_tag(:seating_capacity, nil, {class: "form-control", placeholder: "Enter title"})%>
    </div>

    <div>
      <%= button_tag 'create auditorium', class: "btn btn-default" %>
    </div>
  <% end %>

app/views/admins/new_showing.html.erb
<h1>New Showing</h1>

  <%= form_tag '/showing/create', method: :post do %>
    <div class="form-group">
      <%= label_tag :auditorium_number %>
      <%= text_field_tag(:auditorium_id, nil, {class: "form-control", placeholder: "Enter auditorium number"})%>
    </div>
    <div class="form-group">
      <%= label_tag :movie_title %>
      <%= select_tag "movie_id", options_from_collection_for_select(@movies, "id", "title") %>
    </div>
    <div class="form-group">
      <%= label_tag :start_time %>
      <%= datetime_select("start_time", nil) %>
    </div>
    <div>
      <%= button_tag 'create showing', class: "btn btn-default" %>
    </div>
  <% end %>

app/views/admins/sales.html.erb
<div class="container">
  
  <p>sales</p>

  <div class="dropdown">
  <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
    Select Movie
    <span class="caret"></span>
  </button>
  <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
  <% @movies.each do |movie| %>  
    <li><a href="/sales/?movie_id=<%= movie.id %>"><%= movie.title %></a></li>
  <% end %>
    <li role="separator" class="divider"></li>
    <li><a href="/sales/?movie_id=all">View All Sales</a></li>
  </ul>
  </div>

  <table class="table table-striped">
    <thead>
      <tr>
        <th>Movie</th>
        <th>Auditorium</th>
        <th>customer email</th>
      </tr>
    </thead>
    <% @tickets.each do |ticket| %>
      <tbody>
        <tr>
          <td><%= ticket.showing.movie.title %></td>
          <td><%= ticket.showing.auditorium.id %></td>
          <td><%= ticket.email if ticket.email %></td>
        </tr>
      </tbody>
    <% end %>
  </table>
  
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LaunchpadTicketApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<div id="layout" class="container page-header">
  <h1><%= link_to "Welcome to Launchpad Theaters", movies_path, {:style => 'color:black;'} %></h1>
</div>

<% flash.each do |name, message| %>
  <div class="alert alert-<%= name %> alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= message %>
  </div>
<% end %>

<%= yield %>

</body>
</html>

app/views/movies/edit.html.erb
<div class="container">
  <h3>Edit <%= @movie.title %></h3>

  <%= form_tag "/movies/#{@movie.id}", method: :patch do %>
    <div class="form-group">
      <%= label_tag :title %>
      <%= text_field_tag(:title, "#{@movie.title}", {class: "form-control", placeholder: "Enter title"})%>
    </div>
    <div class="form-group">
      <%= label_tag :description %>
      <%= text_field_tag :description, "#{@movie.description}", class: "form-control", placeholder: "Enter description" %>
    </div>
    <div class="form-group">
      <%= label_tag :image %>
      <%= text_field_tag :image, "#{@movie.image_url}", class: "form-control", placeholder: "Enter the URL of an image" %>
    </div>
    <div class="form-group">
      <%= label_tag :duration %>
      <%= text_field_tag :duration, "#{@movie.duration}", class: "form-control", placeholder: "Enter number of minutes" %>
    </div>
    <div>
      <%= button_tag 'Edit movie', class: "btn btn-default" %>
    </div>
  <% end %>

  <%= link_to 'Back', movies_path %>
</div>

app/views/movies/index.html.erb
<div class="container">

      <% @movies.each do |movie| %>
        <div class="row col-md-3" style="margin:2px;">
          <div class="well">
            <tr>
              <h4 id="title"><%= link_to movie.title, movie_path(movie) %></h4>
              <div onclick="toggleDescription(this)">
                <img src="<%= movie.image_url%>" class="img-responsive">
                <p class="description" style="display:none;"><%= movie.description %></p>
              </div>
              <% if current_user %>
                <%= link_to("Edit movie", edit_movie_path(movie)) %> <br />
                <%= link_to 'Delete movie', movie, method: :delete, data: { confirm: 'Are you sure?' } %>
              <% end %>
            </tr>
          </div>
        </div>
      <% end %>
 

  <br />

  <div class="row">
    <div class="row col-md-12">
      <% if current_user %>
        <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
      <% else %>
        <%= link_to("ADMIN LOG IN", "users/sign_in") %>
      <% end %>  
    </div>
  </div>

</div>

<script>

  var hidden = true;
  toggleDescription = function(movie) {
    var description = movie.getElementsByTagName('p')[0]

    if (hidden) { 
      description.style.display = '';
      hidden = false;
    } else {
      description.style.display = 'none';
      hidden = true;
    }
    
  }

</script>

app/views/movies/new.html.erb
<div class="container">
  <h1>New Movie</h1>

  <%= form_tag '/movies', method: :post do %>
    <div class="form-group">
      <%= label_tag :title %>
      <%= text_field_tag(:title, nil, {class: "form-control", placeholder: "Enter title"})%>
    </div>
    <div class="form-group">
      <%= label_tag :description %>
      <%= text_field_tag :description, nil, class: "form-control", placeholder: "Enter description" %>
    </div>
    <div class="form-group">
      <%= label_tag :image %>
      <%= text_field_tag :image, nil, class: "form-control", placeholder: "Enter the URL of an image" %>
    </div>
    <div class="form-group">
      <%= label_tag :duration %>
      <%= text_field_tag :duration, nil, class: "form-control", placeholder: "Enter number of minutes" %>
    </div>
    <div>
      <%= button_tag 'create movie', class: "btn btn-default" %>
    </div>
  <% end %>

  <%= link_to 'Back', movies_path %>
</div>

app/views/movies/show.html.erb
<div class="container">

  <div class="dropdown">
    <button class="btn btn-default dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
      Select Movie
      <span class="caret"></span>
    </button>
    <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
    <% @movies.each do |movie| %>  
      <li><%= link_to(movie.title, movie_path(movie)) %></li>
    <% end %>
    </ul>
  </div>

  <h2>All Showings of: <%= @movie.title %></h2>
  <table class="table table-striped">
    <thead>
      <tr>
        <th>Time</th>
        <th>Auditorium</th>
        <th>Remaining tickets</th>
      </tr>
    </thead>
    <% @showings.each do |showing| %>
      <tbody>
        <tr>
          <td><%= showing.start_time.strftime("%b %e, %l:%M %p") %></td>
          <td><%= showing.auditorium.id %></td>
          <td><%= showing.remaining_seats %></td>
          <% if showing.remaining_seats > 0 %>
            <td><%= link_to("Buy Ticket", buy_path) %></td>
          <% else %>
            <td>SOLD OUT</td>
          <% end %>
        </tr>
      </tbody>
      <% end %>
  </table>

  <%= link_to("Back", movies_path) %>

</div>

app/views/orders/buy.html.erb
<div class="container">
  <h3>Purchase Ticket for: <%= @showing.movie.title %></h3>
  <h3>Showing at: <%= @showing.start_time.strftime("%b %e, %l:%M %p") %>, in theater <%= @showing.auditorium.id %></h3>

  <%= form_tag "/order/#{@showing.id}", method: :post do %>
    <div class="form-group">
      <%= label_tag :name %>
      <%= text_field_tag(:name, nil, {class: "form-control", placeholder: "Enter name"})%>
    </div>
    <div class="form-group">
      <%= label_tag :email %>
      <%= text_field_tag :email, "#{current_user.email if current_user}", class: "form-control", placeholder: "Enter email" %>
    </div>
    <div class="form-group">
      <%= label_tag :credit_card_number %>
      <%= text_field_tag :credit_card_number, nil, class: "form-control", placeholder: "Enter your 10 digit credit card number" %>
    </div>
    <div class="form-group">
      <%= label_tag :expiration_date %>
      <%= text_field_tag :expiration_date, nil, class: "form-control", placeholder: "Enter the expiration date" %>
    </div>
    <div>
      <%= button_tag 'Buy ticket', class: "btn btn-default" %>
    </div>
  <% end %>

</div>